name: ProjectChucm
main: io.github.mruks.projectchucm.ProjectChucm
version: 1.0
author: MrUks
commands:
 prep:
  description: Preps the server
  usage: /prep <borderLength>
 teamup:
  description: Clears all teams and generates new random teams
  usage: /teamup <numberOfTeams>
 genmap:
  description: generates bedrock borders for the map if the server has been prepped
  usage: /genmap
 ready:
  description: tells the server that the team is ready. When everyone is ready, a 5 second countdown will start after which UHC mode will start 
  usage: /ready
 unready:
  description: tells the server that the team isn't ready 
  usage: /unready
 timer:
  description: sets the timer for how often the server reminds everyone how long the game has been going
  usage: /timer <minuteLength>
 uhcsetup:
  description: spreads the teams and waits until every team confirms to be ready
  usage: /uhcsetup

